import streamlit as st
from collections import OrderedDict

st.set_page_config(page_title="Physics Explorer", layout="wide")

# Physics topics, subtopics, explanations, and SVG animations
physics_data = OrderedDict({
    "Further Mechanics": {
        "introduction": "Dive deeper into the principles of motion and interaction. This section explores the conservation of momentum in various collision scenarios and unravels the kinematics and dynamics of objects moving in circular paths, including the crucial role of centripetal force. Understanding these concepts is key to analyzing how objects behave under the influence of forces.",
        "subsections": OrderedDict({
            "Energy in Collisions": {
                "explanation": "Explores how energy (kinetic and potential) is conserved or transformed during collisions between objects. It distinguishes between elastic collisions (where kinetic energy is conserved) and inelastic collisions (where some kinetic energy is converted to other forms like heat or sound).",
                "svg": "<svg width='120' height='60'><circle cx='30' cy='30' r='15' fill='#0ea5e9'><animate attributeName='cx' values='30;90;30' dur='2s' repeatCount='indefinite'/></circle><circle cx='90' cy='30' r='15' fill='#fbbf24'><animate attributeName='cx' values='90;30;90' dur='2s' repeatCount='indefinite'/></circle></svg>",
            },
            "More Collisions": {
                "explanation": "Likely delves into more complex collision scenarios, possibly involving multiple objects, oblique collisions (not head-on), or impulse (the change in momentum).",
                "svg": "",
            },
            "Circular Motion Basics": {
                "explanation": "Introduces the concepts specific to objects moving in a circular path, such as angular displacement, angular velocity, and angular acceleration.",
                "svg": "<svg width='100' height='100'><circle cx='50' cy='50' r='40' fill='none' stroke='#0ea5e9' stroke-width='2'/><circle id='movingDot' cx='90' cy='50' r='6' fill='#fbbf24'><animateMotion dur='2s' repeatCount='indefinite' path='M40,0 A40,40 0 1,1 -40,0 A40,40 0 1,1 40,0'/></circle></svg>",
            },
            "Centripetal Force": {
                "explanation": "This is a crucial concept. It's the net force that acts towards the center of a circular path, causing an object to continuously change its direction and thus maintain its circular motion. Without it, the object would move in a straight line (due to inertia).",
                "svg": "",
            },
        })
    },
    "Electric and Magnetic Fields": {
        "introduction": "Uncover the fundamental forces governing the electrical and magnetic worlds. This topic examines electric fields generated by charges, the behavior of capacitors in storing energy, and the diverse electromagnetic effects that arise from moving charges and changing fields, including the principles behind motors and electricity generation. These concepts are foundational to much of modern technology.",
        "subsections": OrderedDict({
            "Electric Fields": {
                "explanation": "An electric field is a region around a charged particle or object within which a force would be exerted on other charged particles or objects. It's a way to describe the influence of charges on the space around them.",
                "svg": "<svg width='120' height='60'><circle cx='60' cy='30' r='10' fill='#0ea5e9'/><g><line x1='60' y1='30' x2='100' y2='10' stroke='#fbbf24' stroke-width='2'><animate attributeName='x2' values='100;60;100' dur='2s' repeatCount='indefinite'/></line><line x1='60' y1='30' x2='100' y2='50' stroke='#fbbf24' stroke-width='2'><animate attributeName='x2' values='100;60;100' dur='2s' repeatCount='indefinite'/></line></g></svg>",
            },
            "Radial Electric Fields": {
                "explanation": "Specifically describes the electric field created by a point charge, which radiates outwards (or inwards for a negative charge) in straight lines.",
                "svg": "",
            },
            "Coulomb's Law": {
                "explanation": "This fundamental law quantifies the electrostatic force (attraction or repulsion) between two stationary electrically charged point particles. The force is proportional to the product of the charges and inversely proportional to the square of the distance between them.",
                "svg": "",
            },
            "Capacitor Basics": {
                "explanation": "Introduces capacitors as components that store electrical energy in an electric field. They typically consist of two conductive plates separated by an insulating material (dielectric). Capacitance is the measure of a capacitor's ability to store charge.",
                "svg": "",
            },
            "Charging and Discharging Capacitors": {
                "explanation": "Describes the processes by which capacitors accumulate charge when connected to a voltage source and release that charge when connected to a circuit. This involves understanding time constants.",
                "svg": "",
            },
            "Capacitor Mathematics": {
                "explanation": "Involves equations related to capacitance, charge, voltage, energy stored in a capacitor, and how capacitors behave in series and parallel circuits.",
                "svg": "",
            },
            "Magnetic Fields": {
                "explanation": "A magnetic field is a region around a magnetic material or a moving electric charge within which the force of magnetism acts. It's often visualized using field lines.",
                "svg": "<svg width='120' height='60'><rect x='10' y='20' width='20' height='20' fill='#0ea5e9'/><rect x='90' y='20' width='20' height='20' fill='#fbbf24'/><path d='M30,30 Q60,0 90,30' stroke='#f87171' stroke-width='2' fill='none'><animate attributeName='d' values='M30,30 Q60,0 90,30;M30,30 Q60,60 90,30;M30,30 Q60,0 90,30' dur='2s' repeatCount='indefinite'/></path></svg>",
            },
            "Electric Motors": {
                "explanation": "These devices convert electrical energy into mechanical energy. They operate based on the principle that a current-carrying conductor placed in a magnetic field experiences a force.",
                "svg": "",
            },
            "Magnetic Forces": {
                "explanation": "Explores the forces exerted on moving charges and current-carrying wires within magnetic fields (e.g., the Lorentz force).",
                "svg": "",
            },
            "Generating Electricity (Electromagnetic Induction)": {
                "explanation": "This is the principle behind electric generators. It states that a voltage (and potentially a current, if there's a complete circuit) is induced in a conductor when it is exposed to a changing magnetic field, or when it moves through a magnetic field. Faraday's Law of Induction is key here.",
                "svg": "",
            },
        })
    },
    "Nuclear and Particle Physics": {
        "introduction": "Journey into the subatomic realm to understand the building blocks of matter. This section details our model of the nuclear atom, explores how we probe matter using particle accelerators like the Large Hadron Collider (LHC), and introduces the fascinating 'particle zoo' of fundamental particles and their interactions, governed by the Standard Model.",
        "subsections": OrderedDict({
            "A Nuclear Atom": {
                "explanation": "Focuses on the model of the atom with a dense, positively charged nucleus at its center, containing protons and neutrons, with negatively charged electrons orbiting this nucleus. Rutherford's gold foil experiment is a cornerstone here.",
                "svg": "",
            },
            "Electrons from Atoms": {
                "explanation": "Discusses how electrons can be removed from atoms (ionization) and phenomena related to electron behavior, possibly including thermionic emission or the photoelectric effect.",
                "svg": "",
            },
            "Particle Accelerators": {
                "explanation": "These are machines (like cyclotrons, synchrotrons, and linear accelerators) that use electric fields to accelerate charged particles to very high speeds and energies, and magnetic fields to steer and focus them.",
                "svg": "",
            },
            "Particle Detectors": {
                "explanation": "Devices designed to detect and measure the properties (like energy, momentum, charge) of subatomic particles produced in experiments, often from collisions in accelerators. Examples include Geiger counters, cloud chambers, bubble chambers, and modern electronic detectors.",
                "svg": "",
            },
            "The Large Hadron Collider (LHC)": {
                "explanation": "The world's largest and most powerful particle accelerator, used to collide protons or heavy ions at near the speed of light to study fundamental particles and forces.",
                "svg": "",
            },
            "Particle Interactions": {
                "explanation": "Describes how fundamental particles interact with each other through the fundamental forces (strong nuclear, weak nuclear, electromagnetic, and gravitational).",
                "svg": "",
            },
            "The Particle Zoo": {
                "explanation": "Refers to the large number and variety of subatomic particles discovered, including leptons (like electrons and neutrinos), hadrons (composed of quarks, like protons and neutrons), and bosons (force-carrying particles).",
                "svg": "",
            },
            "Particles and Forces": {
                "explanation": "Elaborates on the Standard Model of particle physics, which classifies all known elementary particles and describes three of the four fundamental forces.",
                "svg": "",
            },
            "Particle Reactions": {
                "explanation": "Examines the processes and conservation laws (like conservation of energy, momentum, charge, lepton number, baryon number) that govern how particles transform or interact.",
                "svg": "",
            },
        })
    },
    "Thermodynamics": {
        "introduction": "Explore the science of energy, heat, and work, and their relationship with the macroscopic properties of matter. This topic defines temperature, details various heat transfer mechanisms, introduces the crucial concept of internal energy, and examines the behavior of ideal gases, laying the groundwork for understanding energy transformations in physical and chemical systems.",
        "subsections": OrderedDict({
            "Heat and Temperature": {
                "explanation": "Differentiates between heat (the transfer of thermal energy between objects due to a temperature difference) and temperature (a measure of the average kinetic energy of the particles in a substance).",
                "svg": "",
            },
            "Heat Transfer": {
                "explanation": "Explores the mechanisms by which heat is transferred: conduction (through direct contact), convection (through the movement of fluids), and radiation (through electromagnetic waves).",
                "svg": "<svg width='120' height='60'><rect x='10' y='20' width='30' height='20' fill='#fbbf24'/><rect x='80' y='20' width='30' height='20' fill='#0ea5e9'/><rect x='40' y='25' width='40' height='10' fill='#fde68a'><animate attributeName='x' values='40;80;40' dur='2s' repeatCount='indefinite'/></rect></svg>",
            },
            "Internal Energy": {
                "explanation": "The total energy contained by a thermodynamic system. It includes the kinetic energy of the particles (due to their motion) and the potential energy associated with the forces between particles.",
                "svg": "",
            },
            "Ideal Gas Behaviour": {
                "explanation": "Introduces the concept of an ideal gas, a theoretical gas composed of many randomly moving point particles that are not subject to interparticle interactions. The ideal gas law (PV=nRT) relates pressure, volume, temperature, and the amount of gas.",
                "svg": "",
            },
        })
    },
    "Nuclear Decay": {
        "introduction": "Investigate the processes of radioactive transformation that occur within unstable atomic nuclei. This section describes the different types of nuclear radiation emitted, the probabilistic nature and rate of radioactive decay (characterized by half-life), and the immense energy released in nuclear fission and fusion reactions.",
        "subsections": OrderedDict({
            "Nuclear Radiation": {
                "explanation": "Describes the different types of radiation emitted from unstable nuclei: alpha particles (helium nuclei), beta particles (electrons or positrons), and gamma rays (high-energy photons).",
                "svg": "<svg width='120' height='60'><circle cx='30' cy='30' r='15' fill='#64748b'/><circle cx='30' cy='30' r='5' fill='#fbbf24'><animate attributeName='cx' values='30;90' dur='2s' repeatCount='indefinite'/></circle></svg>",
            },
            "Rate of Radioactive Decay": {
                "explanation": "Introduces concepts like half-life (the time it takes for half of the radioactive nuclei in a sample to decay) and activity (the rate at which decays occur). Decay is a random, exponential process.",
                "svg": "",
            },
            "Fission and Fusion": {
                "explanation": "Fission: The process where a heavy atomic nucleus (like uranium) splits into two or more lighter nuclei, releasing a large amount of energy. This is the basis for nuclear power plants. Fusion: The process where two light atomic nuclei combine to form a heavier nucleus, also releasing a tremendous amount of energy, powering stars like our Sun.",
                "svg": "",
            },
        })
    },
    "Oscillations": {
        "introduction": "Analyze the ubiquitous phenomenon of periodic motion found in countless natural and engineered systems. This topic focuses on Simple Harmonic Motion (SHM) as a fundamental model for oscillations, delving into its mathematical description, energy transformations, and the important real-world concepts of resonance and damping.",
        "subsections": OrderedDict({
            "Simple Harmonic Motion (SHM)": {
                "explanation": "A specific type of periodic motion where the restoring force is directly proportional to the displacement and acts in the direction opposite to that of displacement (e.g., a mass on a spring, a simple pendulum with small oscillations).",
                "svg": "<svg width='120' height='60'><rect x='10' y='40' width='10' height='20' fill='#0ea5e9'/><rect id='block' x='30' y='40' width='20' height='20' fill='#fbbf24'><animate attributeName='x' values='30;70;30' dur='2s' repeatCount='indefinite'/></rect><line x1='10' y1='50' x2='30' y2='50' stroke='#64748b' stroke-width='3'/></svg>",
            },
            "SHM Mathematics": {
                "explanation": "Involves equations describing displacement, velocity, acceleration, period, frequency, and angular frequency for objects undergoing SHM.",
                "svg": "",
            },
            "SHM Energy": {
                "explanation": "Explores the continuous interchange between kinetic and potential energy in a system undergoing SHM, with the total mechanical energy remaining constant in the absence of damping.",
                "svg": "",
            },
            "Resonance and Damping": {
                "explanation": "Resonance: The phenomenon where the amplitude of oscillation becomes very large when a system is driven at its natural frequency. Damping: The effect that reduces the amplitude of oscillations over time, due to energy losses from resistive forces like friction or air resistance.",
                "svg": "",
            },
        })
    },
    "Astrophysics and Cosmology": {
        "introduction": "Expand your horizons to the grand scale of the universe, from the forces that govern celestial bodies to the origin and fate of the cosmos itself. This section explores gravitational interactions, the life cycle and classification of stars, methods for measuring vast astronomical distances, and our current scientific understanding of the universe's history and ultimate destiny.",
        "subsections": OrderedDict({
            "Gravitational Forces": {
                "explanation": "Based on Newton's Law of Universal Gravitation, which states that every particle attracts every other particle in the universe with a force that is proportional to the product of their masses and inversely proportional to the square of the distance between their centers.",
                "svg": "<svg width='120' height='60'><circle cx='40' cy='30' r='10' fill='#0ea5e9'/><circle cx='80' cy='30' r='15' fill='#fbbf24'/><line x1='40' y1='30' x2='80' y2='30' stroke='#64748b' stroke-width='2'><animate attributeName='x1' values='40;60;40' dur='2s' repeatCount='indefinite'/></line></svg>",
            },
            "Gravitational Fields": {
                "explanation": "A region of space around a massive object where another massive object would experience a gravitational force. Gravitational field strength is the force per unit mass.",
                "svg": "",
            },
            "Starshine (Stellar Radiation)": {
                "explanation": "How stars produce and emit light and other forms of electromagnetic radiation, primarily through nuclear fusion in their cores. Concepts like luminosity and brightness are important.",
                "svg": "",
            },
            "Stellar Classification": {
                "explanation": "Systems for categorizing stars based on their spectral characteristics (which indicate their temperature) and luminosity. The Hertzsprung-Russell (H-R) diagram is a key tool.",
                "svg": "",
            },
            "Distances to the Stars": {
                "explanation": "Methods used to measure the vast distances to stars, such as parallax, standard candles (like Cepheid variables and Type Ia supernovae).",
                "svg": "",
            },
            "The Age of the Universe": {
                "explanation": "How scientists estimate the age of the universe, primarily based on the rate of expansion (Hubble's Law) and observations of the Cosmic Microwave Background radiation. Current estimates are around 13.8 billion years.",
                "svg": "",
            },
            "The Fate of the Universe": {
                "explanation": "Theoretical possibilities for the ultimate destiny of the universe, based on its current expansion rate, density of matter and energy (including dark matter and dark energy). Possibilities include continued expansion forever (Big Freeze/Big Rip) or eventual collapse (Big Crunch).",
                "svg": "",
            },
        })
    },
})

# Sidebar navigation
st.sidebar.title("Physics Explorer")
selected_topic = st.sidebar.selectbox("Select a main topic:", list(physics_data.keys()))

subtopics = []
subsections = physics_data[selected_topic].get("subsections", {})
if isinstance(subsections, dict):
    subtopics = list(subsections.keys())

selected_subtopic = None
if subtopics:
    selected_subtopic = st.sidebar.radio("Sub-topics:", subtopics, key=selected_topic)

# Main content area
st.markdown(f"<h1 style='color:#0369a1;font-size:2.5rem;font-weight:800;margin-bottom:0.5em;'>Physics Explorer</h1>", unsafe_allow_html=True)

if selected_subtopic and isinstance(subsections, dict):
    sub = subsections[selected_subtopic]
    if isinstance(sub, dict):
        st.markdown(f"<h2 style='color:#0ea5e9;font-size:2rem;font-weight:700;margin-bottom:0.2em;'>{selected_subtopic}</h2>", unsafe_allow_html=True)
        if sub.get("svg"):
            st.markdown(sub["svg"], unsafe_allow_html=True)
        st.markdown(f"<div style='font-size:1.1rem;margin-top:1em;margin-bottom:1em;'>{sub.get('explanation','')}</div>", unsafe_allow_html=True)
        st.markdown(f"<div style='color:#64748b;font-size:0.95rem;'><em>Topic: {selected_topic}</em></div>", unsafe_allow_html=True)
else:
    st.markdown(f"<h2 style='color:#0ea5e9;font-size:2rem;font-weight:700;margin-bottom:0.2em;'>{selected_topic}</h2>", unsafe_allow_html=True)
    st.markdown(f"<div style='font-size:1.1rem;margin-top:1em;margin-bottom:1em;'>{physics_data[selected_topic].get('introduction','')}</div>", unsafe_allow_html=True)

# Footer
st.markdown("""
    <hr style='margin-top:2em;margin-bottom:0.5em;border:1px solid #e0e7ef;'>
    <div style='text-align:center;color:#0369a1;font-size:0.95rem;opacity:0.85;'>
        &copy; 2025 Physics Explorer &mdash; UI enhanced by GitHub Copilot
    </div>
    """, unsafe_allow_html=True)
